# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logging/log_envelope.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'logging/log_envelope.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1alogging/log_envelope.proto\x12\x07logging\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf5\x01\n\x0bLogEnvelope\x12\r\n\x05topic\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12 \n\x05level\x18\x03 \x01(\x0e\x32\x11.logging.LogLevel\x12\x0c\n\x04host\x18\x04 \x01(\t\x12\x0f\n\x07service\x18\x05 \x01(\t\x12\x0b\n\x03pid\x18\x06 \x01(\x05\x12\x0c\n\x04type\x18\x07 \x01(\t\x12\x0f\n\x07payload\x18\x08 \x01(\x0c\x12\x0f\n\x07summary\x18\t \x01(\t\x12\x12\n\nsession_id\x18\n \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x0b \x01(\t*\x8c\x01\n\x08LogLevel\x12\x19\n\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x13\n\x0fLOG_LEVEL_DEBUG\x10\x01\x12\x12\n\x0eLOG_LEVEL_INFO\x10\x02\x12\x12\n\x0eLOG_LEVEL_WARN\x10\x03\x12\x13\n\x0fLOG_LEVEL_ERROR\x10\x04\x12\x13\n\x0fLOG_LEVEL_FATAL\x10\x05\x42:Z8github.com/Espeer5/protolog/pkg/logproto/logging;loggingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logging.log_envelope_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/Espeer5/protolog/pkg/logproto/logging;logging'
  _globals['_LOGLEVEL']._serialized_start=321
  _globals['_LOGLEVEL']._serialized_end=461
  _globals['_LOGENVELOPE']._serialized_start=73
  _globals['_LOGENVELOPE']._serialized_end=318
# @@protoc_insertion_point(module_scope)
