# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: demo/demo_message.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'demo/demo_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64\x65mo/demo_message.proto\x12\x04\x64\x65mo\"&\n\x07Message\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"T\n\x06Metric\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x0c\n\x04unit\x18\x03 \x01(\t\x12\x0c\n\x04host\x18\x04 \x01(\t\x12\x11\n\tsubsystem\x18\x05 \x01(\t\"_\n\x05\x41lert\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08severity\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0e\n\x06source\x18\x04 \x01(\t\x12\x13\n\x0bincident_id\x18\x05 \x01(\x03\"_\n\nAuditEvent\x12\r\n\x05\x61\x63tor\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x10\n\x08resource\x18\x03 \x01(\t\x12\x0f\n\x07success\x18\x04 \x01(\x03\x12\x0f\n\x07\x64\x65tails\x18\x05 \x01(\tB4Z2github.com/Espeer5/protolog/pkg/logproto/demo;demob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'demo.demo_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/Espeer5/protolog/pkg/logproto/demo;demo'
  _globals['_MESSAGE']._serialized_start=33
  _globals['_MESSAGE']._serialized_end=71
  _globals['_METRIC']._serialized_start=73
  _globals['_METRIC']._serialized_end=157
  _globals['_ALERT']._serialized_start=159
  _globals['_ALERT']._serialized_end=254
  _globals['_AUDITEVENT']._serialized_start=256
  _globals['_AUDITEVENT']._serialized_end=351
# @@protoc_insertion_point(module_scope)
